/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.BarangController;
import Controller.MemberController;
import Controller.PeminjamanController;
import Controller.UserController;
import Model.Barang;
import Model.Member;
import Model.OperasiCRUD;
import Model.Peminjaman;
import Model.User;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vitky
 */
public class HalamanPetugas extends javax.swing.JFrame {
    DefaultTableModel tabelModel;
    
    UserController uController = new UserController();
    MemberController mController = new MemberController();
    PeminjamanController pController = new PeminjamanController();
    BarangController bController = new BarangController();
    int idMember, idBarang, idPeminjaman, idPetugas;
    private static final DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

    /**
     * Creates new form HalamanPetugas
     */
    public HalamanPetugas() {
        initComponents();
        setVisiblePinjam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sidebar = new javax.swing.JPanel();
        pinjamMenu_btn = new javax.swing.JButton();
        memberMenu_btn = new javax.swing.JButton();
        pageTitle1 = new javax.swing.JLabel();
        barangMenu_btn = new javax.swing.JButton();
        keluarMenu_btn = new javax.swing.JButton();
        Table = new javax.swing.JPanel();
        panelTabelPeminjaman = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPeminjaman = new javax.swing.JTable();
        panelTabelBarang = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelBarang = new javax.swing.JTable();
        panelTabelMember = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelMember = new javax.swing.JTable();
        Form = new javax.swing.JPanel();
        pageTitle = new javax.swing.JLabel();
        formPinjam = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        member_cb = new javax.swing.JComboBox<>();
        barang_cb = new javax.swing.JComboBox<>();
        pinjam_tf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        durasi_tf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        calculate_btn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        total_tf = new javax.swing.JTextField();
        dp_tf = new javax.swing.JTextField();
        kembali_tf = new javax.swing.JTextField();
        addPinjam_btn = new javax.swing.JButton();
        updatePinjam_btn = new javax.swing.JButton();
        deletePinjam_btn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        statusBayar_cb = new javax.swing.JComboBox<>();
        statusPinjam_cb = new javax.swing.JComboBox<>();
        statusDP_cb = new javax.swing.JComboBox<>();
        formBarang = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        barang_tf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        sewa_tf = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        addBarang_btn = new javax.swing.JButton();
        updateBarang_btn = new javax.swing.JButton();
        deleteBarang_btn = new javax.swing.JButton();
        formMember = new javax.swing.JPanel();
        addMember_btn = new javax.swing.JButton();
        updateMember_btn = new javax.swing.JButton();
        deleteMember_btn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        nik_tf = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        nama_tf = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tempat_tf = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tanggal_tf = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jk_tf = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Sidebar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pinjamMenu_btn.setText("Peminjaman");
        pinjamMenu_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinjamMenu_btnActionPerformed(evt);
            }
        });

        memberMenu_btn.setText("Member");
        memberMenu_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberMenu_btnActionPerformed(evt);
            }
        });

        pageTitle1.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        pageTitle1.setText("Petugas Page");

        barangMenu_btn.setText("Barang");
        barangMenu_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangMenu_btnActionPerformed(evt);
            }
        });

        keluarMenu_btn.setText("Keluar");
        keluarMenu_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarMenu_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SidebarLayout = new javax.swing.GroupLayout(Sidebar);
        Sidebar.setLayout(SidebarLayout);
        SidebarLayout.setHorizontalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pinjamMenu_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
            .addComponent(barangMenu_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(memberMenu_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(SidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pageTitle1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(keluarMenu_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SidebarLayout.setVerticalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(pageTitle1)
                .addGap(60, 60, 60)
                .addComponent(pinjamMenu_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barangMenu_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(memberMenu_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(keluarMenu_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabelPeminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPeminjamanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelPeminjaman);

        javax.swing.GroupLayout panelTabelPeminjamanLayout = new javax.swing.GroupLayout(panelTabelPeminjaman);
        panelTabelPeminjaman.setLayout(panelTabelPeminjamanLayout);
        panelTabelPeminjamanLayout.setHorizontalGroup(
            panelTabelPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 988, Short.MAX_VALUE)
            .addGroup(panelTabelPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE))
        );
        panelTabelPeminjamanLayout.setVerticalGroup(
            panelTabelPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
            .addGroup(panelTabelPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTabelPeminjamanLayout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 13, Short.MAX_VALUE)))
        );

        tabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBarangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelBarang);

        javax.swing.GroupLayout panelTabelBarangLayout = new javax.swing.GroupLayout(panelTabelBarang);
        panelTabelBarang.setLayout(panelTabelBarangLayout);
        panelTabelBarangLayout.setHorizontalGroup(
            panelTabelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 959, Short.MAX_VALUE)
            .addGroup(panelTabelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE))
        );
        panelTabelBarangLayout.setVerticalGroup(
            panelTabelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
            .addGroup(panelTabelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTabelBarangLayout.createSequentialGroup()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        tabelMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMemberMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabelMember);

        javax.swing.GroupLayout panelTabelMemberLayout = new javax.swing.GroupLayout(panelTabelMember);
        panelTabelMember.setLayout(panelTabelMemberLayout);
        panelTabelMemberLayout.setHorizontalGroup(
            panelTabelMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 959, Short.MAX_VALUE)
            .addGroup(panelTabelMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE))
        );
        panelTabelMemberLayout.setVerticalGroup(
            panelTabelMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
            .addGroup(panelTabelMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTabelMemberLayout.createSequentialGroup()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout TableLayout = new javax.swing.GroupLayout(Table);
        Table.setLayout(TableLayout);
        TableLayout.setHorizontalGroup(
            TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTabelPeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TableLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelTabelBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TableLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelTabelMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        TableLayout.setVerticalGroup(
            TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTabelPeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TableLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelTabelBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TableLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelTabelMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pageTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pageTitle.setText("Page Title");

        jLabel1.setText("Member");

        jLabel2.setText("Barang");

        jLabel3.setText("Pinjam");

        member_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        barang_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Durasi");

        jLabel5.setText("Hari");

        calculate_btn.setText("Calculate");
        calculate_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculate_btnActionPerformed(evt);
            }
        });

        jLabel6.setText("Total");

        jLabel7.setText("DP 10%");

        jLabel8.setText("Kembali");

        total_tf.setEditable(false);

        dp_tf.setEditable(false);

        kembali_tf.setEditable(false);

        addPinjam_btn.setText("Add");
        addPinjam_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPinjam_btnActionPerformed(evt);
            }
        });

        updatePinjam_btn.setText("Update");
        updatePinjam_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePinjam_btnActionPerformed(evt);
            }
        });

        deletePinjam_btn.setText("Delete");
        deletePinjam_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePinjam_btnActionPerformed(evt);
            }
        });

        jLabel17.setText("S_Bayar");

        jLabel18.setText("S_DP");

        jLabel19.setText("S_Pinjam");

        statusBayar_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum Lunas", "Lunas", " " }));

        statusPinjam_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum", "Sedang", "Selesai" }));

        statusDP_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum Lunas", "Lunas", " " }));

        javax.swing.GroupLayout formPinjamLayout = new javax.swing.GroupLayout(formPinjam);
        formPinjam.setLayout(formPinjamLayout);
        formPinjamLayout.setHorizontalGroup(
            formPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPinjamLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(formPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPinjamLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(29, 29, 29)
                        .addComponent(durasi_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5))
                    .addGroup(formPinjamLayout.createSequentialGroup()
                        .addGroup(formPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(formPinjamLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(26, 26, 26)
                                .addComponent(pinjam_tf))
                            .addGroup(formPinjamLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(25, 25, 25)
                                .addComponent(barang_cb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(formPinjamLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(member_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addComponent(calculate_btn)
                        .addGroup(formPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(formPinjamLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(dp_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(formPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(formPinjamLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel8)
                                    .addGap(18, 18, 18)
                                    .addComponent(kembali_tf))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, formPinjamLayout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(jLabel6)
                                    .addGap(32, 32, 32)
                                    .addComponent(total_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(45, 45, 45)
                        .addGroup(formPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formPinjamLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(statusPinjam_cb, 0, 1, Short.MAX_VALUE))
                            .addGroup(formPinjamLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(formPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(formPinjamLayout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(35, 35, 35)
                                        .addComponent(statusDP_cb, 0, 1, Short.MAX_VALUE))
                                    .addGroup(formPinjamLayout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(18, 18, 18)
                                        .addComponent(statusBayar_cb, 0, 1, Short.MAX_VALUE)))))
                        .addGap(45, 45, 45)
                        .addGroup(formPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addPinjam_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updatePinjam_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deletePinjam_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        formPinjamLayout.setVerticalGroup(
            formPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPinjamLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(formPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPinjamLayout.createSequentialGroup()
                        .addGroup(formPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formPinjamLayout.createSequentialGroup()
                                .addGroup(formPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(member_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(formPinjamLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel1)))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formPinjamLayout.createSequentialGroup()
                                .addComponent(addPinjam_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(formPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(barang_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(calculate_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addComponent(updatePinjam_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(formPinjamLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2)))
                        .addGroup(formPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formPinjamLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel3))
                            .addGroup(formPinjamLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(pinjam_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(formPinjamLayout.createSequentialGroup()
                        .addGroup(formPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(total_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(formPinjamLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel6)))
                        .addGap(18, 18, 18)
                        .addComponent(dp_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(formPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formPinjamLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel8))
                            .addGroup(formPinjamLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(kembali_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(formPinjamLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(formPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statusDP_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)))
                    .addGroup(formPinjamLayout.createSequentialGroup()
                        .addGroup(formPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(statusBayar_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(formPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(statusPinjam_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deletePinjam_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11)
                .addGroup(formPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(durasi_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(formPinjamLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(formPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)))))
        );

        jLabel9.setText("Barang");

        jLabel10.setText("Sewa");

        jLabel11.setText("/Hari");

        addBarang_btn.setText("Add");
        addBarang_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBarang_btnActionPerformed(evt);
            }
        });

        updateBarang_btn.setText("Update");
        updateBarang_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBarang_btnActionPerformed(evt);
            }
        });

        deleteBarang_btn.setText("Delete");
        deleteBarang_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBarang_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formBarangLayout = new javax.swing.GroupLayout(formBarang);
        formBarang.setLayout(formBarangLayout);
        formBarangLayout.setHorizontalGroup(
            formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(formBarangLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(26, 26, 26)
                        .addComponent(barang_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formBarangLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(29, 29, 29)
                        .addComponent(sewa_tf)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBarang_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBarang_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBarang_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(478, Short.MAX_VALUE))
        );
        formBarangLayout.setVerticalGroup(
            formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formBarangLayout.createSequentialGroup()
                        .addComponent(addBarang_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateBarang_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(deleteBarang_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formBarangLayout.createSequentialGroup()
                        .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formBarangLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel9))
                            .addComponent(barang_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sewa_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11))
                            .addGroup(formBarangLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel10)))))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        addMember_btn.setText("Add");
        addMember_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMember_btnActionPerformed(evt);
            }
        });

        updateMember_btn.setText("Update");
        updateMember_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMember_btnActionPerformed(evt);
            }
        });

        deleteMember_btn.setText("Delete");
        deleteMember_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMember_btnActionPerformed(evt);
            }
        });

        jLabel12.setText("NIK");

        jLabel13.setText("Nama");

        jLabel14.setText("Tempat");

        jLabel15.setText("Tanggal");

        jLabel16.setText("JK");

        jk_tf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pria", "Wanita" }));

        javax.swing.GroupLayout formMemberLayout = new javax.swing.GroupLayout(formMember);
        formMember.setLayout(formMemberLayout);
        formMemberLayout.setHorizontalGroup(
            formMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formMemberLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(formMemberLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel12))
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(formMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tempat_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(formMemberLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(nik_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nama_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(formMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(34, 34, 34)
                .addGroup(formMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tanggal_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(jk_tf, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addGroup(formMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addMember_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateMember_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteMember_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        formMemberLayout.setVerticalGroup(
            formMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formMemberLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(formMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formMemberLayout.createSequentialGroup()
                        .addComponent(addMember_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateMember_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(deleteMember_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formMemberLayout.createSequentialGroup()
                        .addGroup(formMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formMemberLayout.createSequentialGroup()
                                .addGroup(formMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(formMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel15)
                                        .addComponent(tanggal_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(formMemberLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel12)))
                                .addGroup(formMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(formMemberLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(formMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addGroup(formMemberLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel13)))
                                        .addGap(24, 24, 24))
                                    .addGroup(formMemberLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jk_tf)
                                        .addGap(14, 14, 14))))
                            .addGroup(formMemberLayout.createSequentialGroup()
                                .addComponent(nik_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nama_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(formMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formMemberLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel14))
                            .addGroup(formMemberLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(tempat_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout FormLayout = new javax.swing.GroupLayout(Form);
        Form.setLayout(FormLayout);
        FormLayout.setHorizontalGroup(
            FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(pageTitle)
                .addContainerGap(844, Short.MAX_VALUE))
            .addGroup(FormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formPinjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FormLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(formBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FormLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(formMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        FormLayout.setVerticalGroup(
            FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(pageTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(formPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormLayout.createSequentialGroup()
                    .addContainerGap(112, Short.MAX_VALUE)
                    .addComponent(formBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormLayout.createSequentialGroup()
                    .addContainerGap(112, Short.MAX_VALUE)
                    .addComponent(formMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void setTableMember(){
        if(mController.getAllMember()==null){
            JOptionPane.showMessageDialog(this,"Daftar Member Tidak Dapat diload");
        }else{
            //resetTable();
            for(Member u : mController.getAllMember()){
                Object[] o = new Object[6];
                o[0] = u.getId();
                o[1] = u.getNIK();
                o[2] = u.getNama();
                o[3] = u.getTempat();
                o[4] = u.getTanggal();
                o[5] = u.getJK();
                tabelModel.addRow(o);
            }
            this.tabelMember.setModel(tabelModel);
        }
    }
    
    private void setTablePinjam(){
        if(mController.getAllMember()==null){
            JOptionPane.showMessageDialog(this,"Daftar Peminjaman Tidak Dapat diload");
        }else{
            //resetTable();
            for(Peminjaman p : pController.getAllPeminjaman()){
                Object[] o = new Object[11];
                o[0] = p.getId();
                o[1] = p.getIdBarang();
                o[2] = p.getIdUser();
                o[3] = p.getDurasi();
                o[4] = p.getTglPinjam();
                o[5] = p.getTglKemabli();
                o[6] = p.getBiaya();
                o[7] = p.getDp();
                o[8] = p.getStatusPinjam();
                o[9] = p.getStatusBayar();
                o[10] = p.getStatusDP();
                tabelModel.addRow(o);
            }
            this.tabelPeminjaman.setModel(tabelModel);
        }
    }
    
    private void setTableBarang(){
        if(bController.getAllBarang()==null){
            JOptionPane.showMessageDialog(this,"Daftar Barang Tidak Dapat diload");
        }else{
            //resetTable();
            for(Barang b : bController.getAllBarang()){
                Object[] o = new Object[6];
                o[0] = b.getId();
                o[1] = b.getNama();
                o[2] = b.getHarga();
                tabelModel.addRow(o);
            }
            this.tabelBarang.setModel(tabelModel);
        }
    }
    
    private void setVisiblePinjam(){
        this.pageTitle.setText("Peminjaman");
        this.formPinjam.setVisible(true);
        this.formBarang.setVisible(false);
        this.formMember.setVisible(false);
        this.panelTabelBarang.setVisible(false);
        this.panelTabelMember.setVisible(false);
        this.panelTabelPeminjaman.setVisible(true);
        tabelModel = new DefaultTableModel();
        tabelModel.setColumnIdentifiers(new String[]{"ID", "Barang", "Member", "Durasi", "Pinjam", "Kembali", "Biaya", "DP", "S_Pinjam", "S_Bayar", "S_DP"});
        setTablePinjam();
        setBarangCB();
        setMemberCB();
    }
    
    private void setVisibleBarang(){
        this.pageTitle.setText("Barang");
        this.formPinjam.setVisible(false);
        this.formBarang.setVisible(true);
        this.formMember.setVisible(false);
        this.panelTabelBarang.setVisible(true);
        this.panelTabelMember.setVisible(false);
        this.panelTabelPeminjaman.setVisible(false);
        tabelModel = new DefaultTableModel();
        tabelModel.setColumnIdentifiers(new String[]{"ID", "Barang", "Harga [per Jam]"});
        setTableBarang();
    }
    
    private void setVisibleMember(){
        this.pageTitle.setText("Member");
        this.formPinjam.setVisible(false);
        this.formBarang.setVisible(false);
        this.formMember.setVisible(true);
        this.panelTabelBarang.setVisible(false);
        this.panelTabelMember.setVisible(true);
        this.panelTabelPeminjaman.setVisible(false);
        tabelModel = new DefaultTableModel();
        tabelModel.setColumnIdentifiers(new String[]{"ID", "NIK","Nama","Tempat", "Tanggal", "JK"});
        setTableMember();
    }
    
    private void resetFormMember(){
        this.nik_tf.setText("");
        this.nama_tf.setText("");
        this.tempat_tf.setText("");
        this.tanggal_tf.setText("");
        this.jk_tf.setSelectedIndex(0);
    }
    
    private void resetFormBarang(){
        this.barang_tf.setText("");
        this.sewa_tf.setText("");
    }
    
    private void resetFormPeminjaman(){
        this.barang_cb.setSelectedIndex(0);
        this.member_cb.setSelectedIndex(0);
        this.pinjam_tf.setText("");
        this.durasi_tf.setText("");
        this.total_tf.setText("");
        this.dp_tf.setText("");
        this.kembali_tf.setText("");
    }
    
    private void setBarangCB(){
        this.barang_cb.removeAllItems();
        if(bController.getAllBarang()==null){
            JOptionPane.showMessageDialog(this, "Daftar barang tidak bisa ditampilkan");
        }else{
            for(Barang b : bController.getAllBarang()){
                this.barang_cb.addItem(b.getId()+" - "+b.getNama()+" - "+b.getHarga());
            }
        }
    }
    
    private void setMemberCB(){
        this.member_cb.removeAllItems();
        if(mController.getAllMember()==null){
            JOptionPane.showMessageDialog(this, "Daftar member tidak bisa ditampilkan");
        }else{
            for(Member m : mController.getAllMember()){
                this.member_cb.addItem(m.getId()+" - "+m.getNama());
            }
        }
    }

    private void pinjamMenu_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinjamMenu_btnActionPerformed
        // TODO add your handling code here:
        setVisiblePinjam();
    }//GEN-LAST:event_pinjamMenu_btnActionPerformed

    private void memberMenu_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberMenu_btnActionPerformed
        // TODO add your handling code here:
        setVisibleMember();
    }//GEN-LAST:event_memberMenu_btnActionPerformed

    private void barangMenu_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangMenu_btnActionPerformed
        // TODO add your handling code here:
        setVisibleBarang();
    }//GEN-LAST:event_barangMenu_btnActionPerformed

    private void tabelPeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPeminjamanMouseClicked
        // TODO add your handling code here:
        int row = this.tabelPeminjaman.getSelectedRow();

        this.idPeminjaman = (int) this.tabelPeminjaman.getValueAt(row, 0);
        for(int i=0; i<this.barang_cb.getItemCount(); i++){
            String barang = this.barang_cb.getItemAt(i);
            String[] barang_split = barang.split(" - ", 3);
            if(barang_split[0].equals(String.valueOf(this.tabelPeminjaman.getValueAt(row, 1)))){
                this.barang_cb.setSelectedIndex(i);
            }
        }
        for(int i=0; i<this.member_cb.getItemCount(); i++){
            String member = this.member_cb.getItemAt(i);
            String[] member_split = member.split(" - ", 2);
            if(member_split[0].equals(String.valueOf(this.tabelPeminjaman.getValueAt(row, 2)))){
                this.member_cb.setSelectedIndex(i);
            }
        }
        this.durasi_tf.setText(String.valueOf(this.tabelPeminjaman.getValueAt(row, 3)));
        this.pinjam_tf.setText(String.valueOf(this.tabelPeminjaman.getValueAt(row, 4)));
        this.kembali_tf.setText(String.valueOf(this.tabelPeminjaman.getValueAt(row, 5)));
        this.total_tf.setText(String.valueOf(this.tabelPeminjaman.getValueAt(row, 6)));
        this.dp_tf.setText(String.valueOf(this.tabelPeminjaman.getValueAt(row, 7)));
        this.statusPinjam_cb.setSelectedIndex((int) this.tabelPeminjaman.getValueAt(row, 8));
        this.statusBayar_cb.setSelectedIndex((int) this.tabelPeminjaman.getValueAt(row, 9));
        this.statusDP_cb.setSelectedIndex((int) this.tabelPeminjaman.getValueAt(row, 10));
    }//GEN-LAST:event_tabelPeminjamanMouseClicked

    private void tabelBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBarangMouseClicked
        // TODO add your handling code here:
        int row = this.tabelBarang.getSelectedRow();

        this.idBarang = (int) this.tabelBarang.getValueAt(row, 0);
        this.barang_tf.setText((String) this.tabelBarang.getValueAt(row, 1));
        this.sewa_tf.setText(String.valueOf(this.tabelBarang.getValueAt(row, 2)));
    }//GEN-LAST:event_tabelBarangMouseClicked

    private void tabelMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMemberMouseClicked
        // TODO add your handling code here:
        int row = this.tabelMember.getSelectedRow();
        int jk = 0;

        this.idMember = (int) this.tabelMember.getValueAt(row, 0);
        this.nik_tf.setText((String) this.tabelMember.getValueAt(row, 1));
        this.nama_tf.setText((String) this.tabelMember.getValueAt(row, 2));
        this.tempat_tf.setText((String) this.tabelMember.getValueAt(row, 3));
        this.tanggal_tf.setText((String) this.tabelMember.getValueAt(row, 4));
        if(this.tabelMember.getValueAt(row, 5).equals("Pria")) jk=0;
        else jk=1;
        this.jk_tf.setSelectedIndex(jk);
    }//GEN-LAST:event_tabelMemberMouseClicked

    private void calculate_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculate_btnActionPerformed
        // TODO add your handling code here:
        String barang = (String) this.barang_cb.getSelectedItem();
        String member = (String) this.member_cb.getSelectedItem();
        String[] barang_split = barang.split(" - ", 3);
        String[] member_split = member.split(" - ", 2);
        String pinjam = this.pinjam_tf.getText();
        int durasi = Integer.valueOf(this.durasi_tf.getText());
        int biaya  = durasi * Integer.valueOf(barang_split[2]);
        int dp = (int) (0.1 * biaya);

        Date pinjamDate = null;
        try {
            pinjamDate = new SimpleDateFormat("yyyy-MM-dd").parse(pinjam);
        } catch (ParseException ex) {
            Logger.getLogger(HalamanPetugas.class.getName()).log(Level.SEVERE, null, ex);
        }

        Calendar c = Calendar.getInstance();
        c.setTime(pinjamDate);
        c.add(Calendar.DATE, durasi);
        Date kembaliDate = c.getTime();
        String kembali = String.valueOf(dateFormat.format(kembaliDate));

        this.kembali_tf.setText(kembali);
        this.total_tf.setText(String.valueOf(biaya));
        this.dp_tf.setText(String.valueOf(dp));
    }//GEN-LAST:event_calculate_btnActionPerformed

    private void addPinjam_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPinjam_btnActionPerformed
        // TODO add your handling code here:
        String barang = (String) this.barang_cb.getSelectedItem();
        String member = (String) this.member_cb.getSelectedItem();
        String[] barang_split = barang.split(" - ", 3);
        String[] member_split = member.split(" - ", 2);
        int barangId = Integer.valueOf(barang_split[0]);
        int memberId = Integer.valueOf(member_split[0]);
        int durasi = Integer.valueOf(this.durasi_tf.getText());
        String pinjam = this.pinjam_tf.getText();
        String kembali = this.kembali_tf.getText();
        int total = Integer.valueOf(this.total_tf.getText());
        int dp = Integer.valueOf(this.dp_tf.getText());
        int statusPinjam = this.statusPinjam_cb.getSelectedIndex();
        int statusDP = this.statusDP_cb.getSelectedIndex();
        int statusBayar = this.statusBayar_cb.getSelectedIndex();

        Peminjaman p = new Peminjaman(barangId, memberId, durasi, pinjam, kembali, total, dp, statusPinjam, statusBayar, statusDP);
        pController.setDml(p, OperasiCRUD.INSERT);
        resetFormPeminjaman();
        setVisiblePinjam();
    }//GEN-LAST:event_addPinjam_btnActionPerformed

    private void updatePinjam_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePinjam_btnActionPerformed
        // TODO add your handling code here:
        int id = this.idPeminjaman;
        String barang = (String) this.barang_cb.getSelectedItem();
        String member = (String) this.member_cb.getSelectedItem();
        String[] barang_split = barang.split(" - ", 3);
        String[] member_split = member.split(" - ", 2);
        int barangId = Integer.valueOf(barang_split[0]);
        int memberId = Integer.valueOf(member_split[0]);
        int durasi = Integer.valueOf(this.durasi_tf.getText());
        String pinjam = this.pinjam_tf.getText();
        String kembali = this.kembali_tf.getText();
        int total = Integer.valueOf(this.total_tf.getText());
        int dp = Integer.valueOf(this.dp_tf.getText());
        int statusPinjam = this.statusPinjam_cb.getSelectedIndex();
        int statusDP = this.statusDP_cb.getSelectedIndex();
        int statusBayar = this.statusBayar_cb.getSelectedIndex();

        Peminjaman p = new Peminjaman(id, barangId, memberId, durasi, pinjam, kembali, total, dp, statusPinjam, statusBayar, statusDP);
        pController.setDml(p, OperasiCRUD.UPDATE);
        resetFormPeminjaman();
        setVisiblePinjam();
    }//GEN-LAST:event_updatePinjam_btnActionPerformed

    private void deletePinjam_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePinjam_btnActionPerformed
        // TODO add your handling code here:
        int id = this.idPeminjaman;

        Peminjaman p = new Peminjaman(id);
        pController.setDml(p, OperasiCRUD.DELETE);
        resetFormPeminjaman();
        setVisiblePinjam();
    }//GEN-LAST:event_deletePinjam_btnActionPerformed

    private void addBarang_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBarang_btnActionPerformed
        // TODO add your handling code here:
        String barang = this.barang_tf.getText();
        int harga = Integer.valueOf(this.sewa_tf.getText());

        Barang b = new Barang(barang, harga);
        bController.setDml(b, OperasiCRUD.INSERT);
        resetFormBarang();
        setVisibleBarang();
    }//GEN-LAST:event_addBarang_btnActionPerformed

    private void updateBarang_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBarang_btnActionPerformed
        // TODO add your handling code here:
        int id = this.idBarang;
        String barang = this.barang_tf.getText();
        int harga = Integer.valueOf(this.sewa_tf.getText());

        Barang b = new Barang(id, barang, harga);
        bController.setDml(b, OperasiCRUD.UPDATE);
        resetFormBarang();
        setVisibleBarang();
    }//GEN-LAST:event_updateBarang_btnActionPerformed

    private void deleteBarang_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBarang_btnActionPerformed
        // TODO add your handling code here:
        int id = this.idBarang;

        Barang b = new Barang(id);
        bController.setDml(b, OperasiCRUD.DELETE);
        resetFormBarang();
        setVisibleBarang();
    }//GEN-LAST:event_deleteBarang_btnActionPerformed

    private void addMember_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMember_btnActionPerformed
        // TODO add your handling code here:
        String nik = this.nik_tf.getText();
        String nama = this.nama_tf.getText();
        String tempat = this.tempat_tf.getText();
        String tanggal = this.tanggal_tf.getText();
        String jk = String.valueOf(this.jk_tf.getSelectedItem());

        Member m = new Member(nik, nama, tempat, tanggal, jk);
        mController.setDml(m, OperasiCRUD.INSERT);
        resetFormMember();
        setVisibleMember();
    }//GEN-LAST:event_addMember_btnActionPerformed

    private void updateMember_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMember_btnActionPerformed
        // TODO add your handling code here:
        int id = this.idMember;
        String nik = this.nik_tf.getText();
        String nama = this.nama_tf.getText();
        String tempat = this.tempat_tf.getText();
        String tanggal = this.tanggal_tf.getText();
        String jk = String.valueOf(this.jk_tf.getSelectedItem());

        Member m = new Member(id, nik, nama, tempat, tanggal, jk);
        mController.setDml(m, OperasiCRUD.UPDATE);
        resetFormMember();
        setVisibleMember();
    }//GEN-LAST:event_updateMember_btnActionPerformed

    private void deleteMember_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMember_btnActionPerformed
        // TODO add your handling code here:
        int id = this.idMember;

        Member m = new Member(id);
        mController.setDml(m, OperasiCRUD.DELETE);
        resetFormMember();
        setVisibleMember();
    }//GEN-LAST:event_deleteMember_btnActionPerformed

    private void keluarMenu_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarMenu_btnActionPerformed
        // TODO add your handling code here:
        uController.logout(this);
    }//GEN-LAST:event_keluarMenu_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanPetugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Form;
    private javax.swing.JPanel Sidebar;
    private javax.swing.JPanel Table;
    private javax.swing.JButton addBarang_btn;
    private javax.swing.JButton addMember_btn;
    private javax.swing.JButton addPinjam_btn;
    private javax.swing.JButton barangMenu_btn;
    private javax.swing.JComboBox<String> barang_cb;
    private javax.swing.JTextField barang_tf;
    private javax.swing.JButton calculate_btn;
    private javax.swing.JButton deleteBarang_btn;
    private javax.swing.JButton deleteMember_btn;
    private javax.swing.JButton deletePinjam_btn;
    private javax.swing.JTextField dp_tf;
    private javax.swing.JTextField durasi_tf;
    private javax.swing.JPanel formBarang;
    private javax.swing.JPanel formMember;
    private javax.swing.JPanel formPinjam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JComboBox<String> jk_tf;
    private javax.swing.JButton keluarMenu_btn;
    private javax.swing.JTextField kembali_tf;
    private javax.swing.JButton memberMenu_btn;
    private javax.swing.JComboBox<String> member_cb;
    private javax.swing.JTextField nama_tf;
    private javax.swing.JTextField nik_tf;
    private javax.swing.JLabel pageTitle;
    private javax.swing.JLabel pageTitle1;
    private javax.swing.JPanel panelTabelBarang;
    private javax.swing.JPanel panelTabelMember;
    private javax.swing.JPanel panelTabelPeminjaman;
    private javax.swing.JButton pinjamMenu_btn;
    private javax.swing.JTextField pinjam_tf;
    private javax.swing.JTextField sewa_tf;
    private javax.swing.JComboBox<String> statusBayar_cb;
    private javax.swing.JComboBox<String> statusDP_cb;
    private javax.swing.JComboBox<String> statusPinjam_cb;
    private javax.swing.JTable tabelBarang;
    private javax.swing.JTable tabelMember;
    private javax.swing.JTable tabelPeminjaman;
    private javax.swing.JTextField tanggal_tf;
    private javax.swing.JTextField tempat_tf;
    private javax.swing.JTextField total_tf;
    private javax.swing.JButton updateBarang_btn;
    private javax.swing.JButton updateMember_btn;
    private javax.swing.JButton updatePinjam_btn;
    // End of variables declaration//GEN-END:variables
}
